version: 2

before:
  hooks:
    - go mod tidy
    # Note: whisper.cpp binaries are built in CI matrix and combined here

builds:
  - main: ./cmd/ghospel
    id: "ghospel"
    binary: ghospel
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64  # Disabled due to whisper.cpp cross-compilation issues (see issue #1)
    env:
      - CGO_ENABLED=0
    tags:
      - release
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

# Homebrew tap removed - focusing on GitHub releases only
# See issue for future Homebrew support

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: '🚀 Features'
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: '🐛 Bug Fixes'
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: '🔧 Improvements'
      regexp: '^.*?(refactor|perf)(\(.+\))??!?:.+$'
      order: 2
    - title: '📚 Documentation'
      regexp: '^.*?docs(\(.+\))??!?:.+$'
      order: 3
    - title: '🧪 Testing'
      regexp: '^.*?test(\(.+\))??!?:.+$'
      order: 4
    - title: '💥 Breaking Changes'
      regexp: '^.*?!:.+$'
      order: 5
    - title: 'Other Changes'
      order: 999